name: project-pytests

on:
  push:
    branches: [ "main" ]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Install CUDA
        uses: Jimver/cuda-toolkit@v0.2.23
        with: 
          cuda: 12.8
      - name: Setup Cmake
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake curl python3 python3-venv
      - name: Build package
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug
      - name: Install Poetry (dependency management)
        run: curl -sSL https://install.python-poetry.org | python3 -
      - name: Install Python dependencies
        run: poetry lock && poetry install
      - name: Run tests
        run: poetry run pytest tests/pytorch_stress_test.py


